proyecto/cursodj/cursodj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('generales.urls','generales'), namespace='generales')),
    path('catalogos/', include(('catalogos.urls','catalogos'), namespace='catalogos')),
    path('admin/', admin.site.urls),
]

proyecto/cursodj/generales/urls.py
from django.urls import path, include

from generales.views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
]

proyecto/cursodj/catalogos/models.py
from django.db import models

# Create your models here.

proyecto/cursodj/catalogos/views.py
from django.shortcuts import render

# Create your views here.

proyecto/cursodj/generales/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.views import generic
# Create your views here.
class HomePage(generic.View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Pagina de Inicio')


class Home(generic.TemplateView):
    template_name = 'generales/home.html'

proyecto/cursodj/generales/templates/generales/home.html
{% extends 'base/base.html' %}
{% block head_title %}
Inicio del sitio
{% endblock head_title %}
{% block contenido %}
<h1>Bienvenidos al home de la aplicación del curso de Django Práctico.</h1>
{% endblock contenido %}

proyecto/cursodj/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
    {% block head_title %}
    Curso Django Práctico - Creando APP Facturación
    {% endblock head_title %}    
  </title>
  <!-- Bootstrap Core CSS -->
  <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- MetisMenu CSS -->
  <link href="{% static 'base/css/metisMenu.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="{% static 'base/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

</head>

<body id="page-top">

  <div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'generales:home' %}">Curso Django</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"><i class="fa fa-cogs fa-fw"></i> Catálogos <span class="fa arrow"></span></a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    {% block contenido %}Blank{% endblock contenido %}
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="{% static 'base/js/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'base/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'base/js/metisMenu.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'base/js/sb-admin-2.js' %}"></script>

</body>

</html>